import logging
import requests
import os

logger = logging.getLogger(__name__)

class PublicationService:
    def __init__(self):
        self.webhook_url = os.getenv("ZAPIER_WEBHOOK_URL")

    def publish_video(self, video_path: str, metadata: dict):
        """
        Triggers a Zapier webhook to publish the video.
        
        Args:
            video_path (str): Path to the video file (might need to upload to cloud first in real scenario).
            metadata (dict): Title, description, hashtags.
        """
        logger.info("Publishing video via Zapier...")
        
        if not self.webhook_url:
            logger.warning("ZAPIER_WEBHOOK_URL not set. Skipping publication.")
            return

        # In a real production environment, we would upload the video to S3/Cloudinary 
        # and send the URL to Zapier. For this MVP, we'll simulate sending the file 
        # or assume the webhook can handle a file upload (which Zapier can, but it's complex).
        # We'll send metadata and a placeholder URL.
        
        payload = {
            "title": metadata.get("title", "New AI Video"),
            "description": metadata.get("description", "Generated by AI Agent"),
            "hashtags": metadata.get("hashtags", "#AI #Education"),
            "video_filename": os.path.basename(video_path)
            # "video_url": "..." 
        }
        
        try:
            response = requests.post(self.webhook_url, json=payload)
            response.raise_for_status()
            logger.info("Publication webhook triggered successfully.")
            
        except Exception as e:
            logger.error(f"Error triggering publication webhook: {e}")
